import os
import torch
import math
import numpy as np
import sys

class StreamWriter:
    def __init__(self, filename, args, geom_path, cell_path, lattice_type="unknown", centering="P"):
        self.filename = filename
        self.args = args
        self.geom_path = geom_path
        self.cell_path = cell_path
        self.lattice_type = lattice_type
        self.centering = centering
        self.write_header()

    def write_header(self):
        with open(self.filename, 'w') as f:
            cmd = "python " + " ".join(sys.argv)
            f.write(f"Generated by PyTorch PinkIndexer\n{cmd}\n")
            f.write("----- Begin geometry file -----\n")
            try:
                with open(self.geom_path, 'r') as g: f.write(g.read())
            except: f.write("; Error reading geometry\n")
            f.write("\n----- End geometry file -----\n")
            f.write("----- Begin unit cell -----\n")
            try:
                with open(self.cell_path, 'r') as c: f.write(c.read())
            except: f.write("; Error reading cell\n")
            f.write("----- End unit cell -----\n")
            f.write("Indexing methods selected: pinkindexer\n")

    def write_chunk(self, result_dict):
        out = []
        out.append("----- Begin chunk -----")
        out.append(f"Image filename: {result_dict['filename']}")
        out.append(f"Event: //{result_dict['event']}")
        out.append(f"Image serial number: {result_dict.get('serial', 0)}")
        
        # Check acceptance status
        accepted = result_dict.get('accepted', False)
        
        if accepted:
            out.append("hit = 1")
            out.append("indexed_by = pinkindexer-pytorch")
            
            eV = result_dict['beam_energy_eV']
            clen = result_dict['detector_distance_m']
            out.append(f"photon_energy_eV = {eV:.6f}")
            out.append(f"average_camera_length = {clen:.6f} m")
            
            dx_mm = result_dict.get('refined_dx', 0.0) * 1000.0
            dy_mm = result_dict.get('refined_dy', 0.0) * 1000.0

            init_x_mm = result_dict.get('initial_shift_x', 0.0) * 1000.0
            init_y_mm = result_dict.get('initial_shift_y', 0.0) * 1000.0

            diff_x_mm = dx_mm - init_x_mm
            diff_y_mm = dy_mm - init_y_mm

            out.append(f"header/float//center/shift_x_mm = { init_x_mm:.6f}")
            out.append(f"header/float//center/shift_y_mm = { init_y_mm:.6f}")

            peaks_raw = result_dict['input_peaks_raw'] 
            intensities = result_dict['input_intensities']
            
            out.append(f"num_peaks = {len(peaks_raw)}")
            out.append("Peaks from peak search")
            out.append("  fs/px   ss/px (1/d)/nm^-1   Intensity  Panel")
            
            lam = 1.0 / result_dict['k0_Ainv']
            pixel_size = result_dict['pixel_size_m']
            
            for i in range(len(peaks_raw)):
                fs_px, ss_px = peaks_raw[i, 0], peaks_raw[i, 1]
                x_m = (fs_px - 512) * pixel_size 
                y_m = (ss_px - 512) * pixel_size
                r = math.sqrt(x_m**2 + y_m**2)
                theta = math.atan2(r, clen)
                inv_d_nm = (2 * math.sin(theta/2.0) / lam) * 10.0 
                
                I = intensities[i] if intensities is not None else 0.0
                out.append(f"{fs_px:8.2f} {ss_px:8.2f} {inv_d_nm:10.2f} {I:10.2f}    p0")
            
            out.append("End of peak list")

            out.append("--- Begin crystal")
            B = result_dict['final_B']
            R = result_dict['final_R']
            
            # 1. Correct rotation: Lab frame B is R @ B (columns are a*, b*, c*)
            # B_rot = torch.mm(R, B).cpu().numpy()
            B_rot = R @ B
            
            # 2. Extract columns, not rows
            astar = B_rot[:, 0] * 10.0 
            bstar = B_rot[:, 1] * 10.0
            cstar = B_rot[:, 2] * 10.0
            
            out.append(f"astar = {astar[0]:+.7f} {astar[1]:+.7f} {astar[2]:+.7f} nm^-1")
            out.append(f"bstar = {bstar[0]:+.7f} {bstar[1]:+.7f} {bstar[2]:+.7f} nm^-1")
            out.append(f"cstar = {cstar[0]:+.7f} {cstar[1]:+.7f} {cstar[2]:+.7f} nm^-1")

            try:
                # 3. Real space vectors are the columns of the transposed inverse
                A = np.linalg.inv(B_rot.T)
                a_vec = A[:, 0]
                b_vec = A[:, 1]
                c_vec = A[:, 2]
                
                a_nm = np.linalg.norm(a_vec) / 10.0
                b_nm = np.linalg.norm(b_vec) / 10.0
                c_nm = np.linalg.norm(c_vec) / 10.0
                
                # 4. Calculate actual angles using dot products
                al_deg = np.rad2deg(np.arccos(np.dot(b_vec, c_vec) / (np.linalg.norm(b_vec) * np.linalg.norm(c_vec))))
                be_deg = np.rad2deg(np.arccos(np.dot(a_vec, c_vec) / (np.linalg.norm(a_vec) * np.linalg.norm(c_vec))))
                ga_deg = np.rad2deg(np.arccos(np.dot(a_vec, b_vec) / (np.linalg.norm(a_vec) * np.linalg.norm(b_vec))))
                
                out.append(f"Cell parameters {a_nm:.5f} {b_nm:.5f} {c_nm:.5f} nm, {al_deg:.5f} {be_deg:.5f} {ga_deg:.5f} deg")
            except:
                out.append("Cell parameters 0.0 0.0 0.0 nm, 0 0 0 deg")

            res_limit_Ainv = result_dict.get('diffraction_resolution_limit_Ainv', 0.0)
            res_limit_nm_inv = res_limit_Ainv * 10.0
            res_limit = 1.0 / res_limit_Ainv
            out.append(f"diffraction_resolution_limit = {res_limit_nm_inv:.2f} nm^-1 or {res_limit:.2f} A")

            out.append(f"lattice_type = {self.lattice_type}")
            out.append(f"centering = {self.centering}")
            out.append(f"predict_refine/det_shift x = {diff_x_mm:.5f} y = {diff_y_mm:.5f} mm")
            
            refl_hkl = result_dict['refl_hkl']
            refl_pred = result_dict['refl_pred_pix']
            refl_I = result_dict['refl_I']
            refl_sigma = result_dict['refl_sigma']
            refl_bg = result_dict['refl_bg']
            refl_pk = result_dict['refl_peak']
            
            out.append(f"num_reflections = {len(refl_hkl)}")
            out.append("Reflections measured after indexing")
            out.append("   h    k    l          I   sigma(I)       peak background  fs/px  ss/px panel")
            
            for i in range(len(refl_hkl)):
                h, k, l = int(refl_hkl[i,0]), int(refl_hkl[i,1]), int(refl_hkl[i,2])
                fs, ss = refl_pred[i,0], refl_pred[i,1]
                I = refl_I[i]
                sig = refl_sigma[i]
                bg = refl_bg[i]
                pk = refl_pk[i]
                
                # CrystFEL Format: h k l I sigma peak bg fs ss panel
                out.append(f"{h:4d} {k:4d} {l:4d} {I:10.2f} {sig:10.2f} {pk:10.2f} {bg:10.2f} {fs:6.1f} {ss:6.1f} p0")
                
            out.append("End of reflections")
            out.append("--- End crystal")
        else:
            # Solution Rejected
            out.append("hit = 0")
            out.append(f"indexed_by = none")
            # Usually we do NOT write peak lists or crystal info for hit=0 to save space, 
            # unless debugging. Here we skip crystal info as is standard.
        
        out.append("----- End chunk -----\n")
        
        with open(self.filename, 'a') as f:
            f.write('\n'.join(out))
